# Generated by Django 4.2.2 on 2023-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_at',
            field=models.DateField(null=True),
        ),
    ]
